### ISSUE TITLE
Keen in WebUSB/WebHID support?

### ISSUE THREAD

**Issue by jraoult** [asutherland/ni-controllers-lib#2]
Thanks for your work on Maschine MK3 support @asutherland. I'm glad I found this library because I was struggling to get it done in JS. My target is actually the web platform (Chromium likes for now). So I took your code and abstracted the USB (and HID) bits to use WebUSB and WebHID.

My first question is have you ever considered creating a PR to the upstream (https://github.com/met5678/node-traktor-f1) with your changes? This is for now the only version published to NPM and your work is a very nice addition. Alternatively what about publishing your fork which sees to be way more advanced?

Second, would you consider a PR with my changes. The idea is to enable the end user to switch the USB comms implementation so that the library can be used in Node or the web.

WDYT?

**Comment by asutherland** [comment]
> My first question is have you ever considered creating a PR to the upstream (https://github.com/met5678/node-traktor-f1) with your changes?

My initial upstreaming cleanup at https://github.com/met5678/node-traktor-f1/pull/1 didn't receive any feedback, so I've haven't pursued additional upstreaming.

> Alternatively what about publishing your fork which sees to be way more advanced?

I can certainly do that for visibility.  Any naming suggestions?

> Second, would you consider a PR with my changes.

Absolutely!  While it doesn't seem likely that WebUSB/WebHID will get cross-browser support anytime soon, it's definitely a better runtime situation than what the node.js situation requires.

**Comment by jraoult** [comment]
> I can certainly do that for visibility. Any naming suggestions?

I didn't think about it but you are right that the scope is broader than _traktor_ now and will be for more than just the _node_ runtime. Something like **_ni-controllers-lib_**? I know it is not glamorous but it would be easy to find and describes what it is.

> Absolutely! While it doesn't seem likely that WebUSB/WebHID will get cross-browser support anytime soon, it's definitely a better runtime situation than what the node.js situation requires.

I'll obviously make sure than both runtime are fully handled.

Last question regarding the Maschine MK3. Am I right to think that you haven't handled the encoder wheel rotation yet (offset 11 here //https://github.com/Drachenkaetzchen/cabl/blob/develop/doc/hardware/maschine-mk3/MaschineMK3-HIDInput.md)?

**Comment by jraoult** [comment]
> Correct. I suppose that counts as one of the "steppers" like the F1 already has support for.

I need to dig a little more but it looks like it goes cyclicly from 0 to 15 and then starts again to 0, so not really like stepper.

I'll start creating PR on your repo then. We can figure out naming/publishing down the line.

Last question before I commit to it. I actually converted the codebase to typescript. It helped me while browsing the source code because I could get auto-completion and type-checking. Is it something you would consider or you would rather stay with JS? Happy to strip down the types if you prefer.

**Comment by asutherland** [comment]
> I need to dig a little more but it looks like it goes cyclicly from 0 to 15 and then starts again to 0, so not really like stepper.
 
The comment at the top of https://github.com/asutherland/node-traktor-f1/blob/maschine-mk3/lib/components/input/stepwheel.js claims it was expecting a 4-bit value (and then fails to handle wraparound unless I'm missing something.)

> I'll start creating PR on your repo then. We can figure out naming/publishing down the line.

Sounds good!

> Last question before I commit to it. I actually converted the codebase to typescript. It helped me while browsing the source code because I could get auto-completion and type-checking. Is it something you would consider or you would rather stay with JS? Happy to strip down the types if you prefer.

I'm fine to convert to typescript.  Haven't had much experience with it in practice, but I'd be interested to experience the the fancy VSCode support and in general see if it seems like I should move my taskolio project to typescript or if I should (over a much longer process) migrate to Rust.
